// @generated
// This file is @generated by prost-build.
// Note: The protobuf definition is shared between the Rust and Swift parts.
// We are not using prost-build because providing protoc is a hassle on many platforms.
// See .github/workflows/autofix.yml for how to update the respective files,
// or file a PR and let CI handle it.

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InterceptConf {
    #[prost(bool, tag="1")]
    pub default: bool,
    #[prost(string, repeated, tag="2")]
    pub actions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint32, tag="3")]
    pub agent_pid: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    #[prost(oneof="message::Message", tags="1, 2, 3, 4")]
    pub message: ::core::option::Option<message::Message>,
}
/// Nested message and enum types in `Message`.
pub mod message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag="1")]
        Flow(super::NewFlow),
        #[prost(message, tag="2")]
        SocketOpenEvent(super::SocketOpenEvent),
        #[prost(message, tag="3")]
        SocketCloseEvent(super::SocketCloseEvent),
        #[prost(message, tag="4")]
        SocketDataEvent(super::SocketDataEvent),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NewFlow {
    #[prost(oneof="new_flow::Message", tags="1, 2")]
    pub message: ::core::option::Option<new_flow::Message>,
}
/// Nested message and enum types in `NewFlow`.
pub mod new_flow {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag="1")]
        Tcp(super::TcpFlow),
        #[prost(message, tag="2")]
        Udp(super::UdpFlow),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TcpFlow {
    #[prost(message, optional, tag="1")]
    pub remote_address: ::core::option::Option<Address>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UdpFlow {
    #[prost(message, optional, tag="1")]
    pub local_address: ::core::option::Option<Address>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UdpPacket {
    #[prost(bytes="vec", tag="1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="2")]
    pub remote_address: ::core::option::Option<Address>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Address {
    #[prost(string, tag="1")]
    pub host: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub port: u32,
    #[prost(string, tag="3")]
    pub version: ::prost::alloc::string::String,
    #[prost(uint32, tag="4")]
    pub src_port: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SocketOpenEvent {
    #[prost(uint64, tag="1")]
    pub time_stamp_nano: u64,
    #[prost(uint32, tag="2")]
    pub pid: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SocketCloseEvent {
    #[prost(uint64, tag="1")]
    pub time_stamp_nano: u64,
    #[prost(uint32, tag="2")]
    pub pid: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SocketDataEvent {
    #[prost(uint64, tag="1")]
    pub entry_time_stamp_nano: u64,
    #[prost(uint64, tag="2")]
    pub time_stamp_nano: u64,
    #[prost(uint32, tag="3")]
    pub pid: u32,
    #[prost(bool, tag="4")]
    pub direction: bool,
    #[prost(uint64, tag="5")]
    pub msg_size: u64,
    #[prost(bytes="vec", tag="6")]
    pub msg: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag="7")]
    pub validate_read_bytes: i64,
    #[prost(int64, tag="8")]
    pub validate_written_bytes: i64,
}
// @@protoc_insertion_point(module)
